// This file will be auto-generated by Supabase CLI
// Run: pnpm supabase:gen-types to generate actual types

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            profiles: {
                Row: {
                    id: string
                    user_id: string
                    bio: string | null
                    social_links: Json | null
                    preferences: Json | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    bio?: string | null
                    social_links?: Json | null
                    preferences?: Json | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    bio?: string | null
                    social_links?: Json | null
                    preferences?: Json | null
                    created_at?: string
                    updated_at?: string
                }
                Relationships: []
            }
            tournaments: {
                Row: {
                    id: string
                    title: string
                    description: string | null
                    type: string
                    status: string
                    creator_id: string
                    max_participants: number | null
                    registration_deadline: string | null
                    start_date: string | null
                    end_date: string | null
                    rules: Json | null
                    settings: Json | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    title: string
                    description?: string | null
                    type: string
                    status?: string
                    creator_id: string
                    max_participants?: number | null
                    registration_deadline?: string | null
                    start_date?: string | null
                    end_date?: string | null
                    rules?: Json | null
                    settings?: Json | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    title?: string
                    description?: string | null
                    type?: string
                    status?: string
                    creator_id?: string
                    max_participants?: number | null
                    registration_deadline?: string | null
                    start_date?: string | null
                    end_date?: string | null
                    rules?: Json | null
                    settings?: Json | null
                    created_at?: string
                    updated_at?: string
                }
                Relationships: []
            }
            teams: {
                Row: {
                    id: string
                    name: string
                    logo_url: string | null
                    description: string | null
                    captain_id: string | null
                    tournament_id: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    logo_url?: string | null
                    description?: string | null
                    captain_id?: string | null
                    tournament_id?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    logo_url?: string | null
                    description?: string | null
                    captain_id?: string | null
                    tournament_id?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Relationships: [
                    {
                        foreignKeyName: "teams_tournament_id_fkey"
                        columns: ["tournament_id"]
                        referencedRelation: "tournaments"
                        referencedColumns: ["id"]
                    }
                ]
            }
            players: {
                Row: {
                    id: string
                    name: string
                    email: string | null
                    avatar_url: string | null
                    team_id: string | null
                    position: string | null
                    jersey_number: number | null
                    stats: Json | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    email?: string | null
                    avatar_url?: string | null
                    team_id?: string | null
                    position?: string | null
                    jersey_number?: number | null
                    stats?: Json | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    email?: string | null
                    avatar_url?: string | null
                    team_id?: string | null
                    position?: string | null
                    jersey_number?: number | null
                    stats?: Json | null
                    created_at?: string
                    updated_at?: string
                }
                Relationships: [
                    {
                        foreignKeyName: "players_team_id_fkey"
                        columns: ["team_id"]
                        referencedRelation: "teams"
                        referencedColumns: ["id"]
                    }
                ]
            }
            matches: {
                Row: {
                    id: string
                    tournament_id: string
                    round: number | null
                    match_number: number | null
                    team1_id: string | null
                    team2_id: string | null
                    scheduled_at: string | null
                    started_at: string | null
                    completed_at: string | null
                    status: string
                    venue: string | null
                    notes: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    tournament_id: string
                    round?: number | null
                    match_number?: number | null
                    team1_id?: string | null
                    team2_id?: string | null
                    scheduled_at?: string | null
                    started_at?: string | null
                    completed_at?: string | null
                    status?: string
                    venue?: string | null
                    notes?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    tournament_id?: string
                    round?: number | null
                    match_number?: number | null
                    team1_id?: string | null
                    team2_id?: string | null
                    scheduled_at?: string | null
                    started_at?: string | null
                    completed_at?: string | null
                    status?: string
                    venue?: string | null
                    notes?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Relationships: [
                    {
                        foreignKeyName: "matches_tournament_id_fkey"
                        columns: ["tournament_id"]
                        referencedRelation: "tournaments"
                        referencedColumns: ["id"]
                    },
                    {
                        foreignKeyName: "matches_team1_id_fkey"
                        columns: ["team1_id"]
                        referencedRelation: "teams"
                        referencedColumns: ["id"]
                    },
                    {
                        foreignKeyName: "matches_team2_id_fkey"
                        columns: ["team2_id"]
                        referencedRelation: "teams"
                        referencedColumns: ["id"]
                    }
                ]
            }
            match_results: {
                Row: {
                    id: string
                    match_id: string
                    winner_id: string | null
                    team1_score: number | null
                    team2_score: number | null
                    details: Json | null
                    verified: boolean
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    match_id: string
                    winner_id?: string | null
                    team1_score?: number | null
                    team2_score?: number | null
                    details?: Json | null
                    verified?: boolean
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    match_id?: string
                    winner_id?: string | null
                    team1_score?: number | null
                    team2_score?: number | null
                    details?: Json | null
                    verified?: boolean
                    created_at?: string
                    updated_at?: string
                }
                Relationships: [
                    {
                        foreignKeyName: "match_results_match_id_fkey"
                        columns: ["match_id"]
                        referencedRelation: "matches"
                        referencedColumns: ["id"]
                    }
                ]
            }
            media: {
                Row: {
                    id: string
                    user_id: string
                    tournament_id: string | null
                    team_id: string | null
                    match_id: string | null
                    type: string
                    url: string
                    thumbnail_url: string | null
                    caption: string | null
                    file_size: number | null
                    mime_type: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    tournament_id?: string | null
                    team_id?: string | null
                    match_id?: string | null
                    type: string
                    url: string
                    thumbnail_url?: string | null
                    caption?: string | null
                    file_size?: number | null
                    mime_type?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    tournament_id?: string | null
                    team_id?: string | null
                    match_id?: string | null
                    type?: string
                    url?: string
                    thumbnail_url?: string | null
                    caption?: string | null
                    file_size?: number | null
                    mime_type?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Relationships: []
            }
        }
        Views: {
            [_ in never]: never
        }
        Functions: {
            [_ in never]: never
        }
        Enums: {
            [_ in never]: never
        }
        CompositeTypes: {
            [_ in never]: never
        }
    }
} 